FROM python:3.12-slim

WORKDIR /app

# Install system dependencies:
#   ffmpeg   — required for video encoding and cover extraction
#   curl     — required to download biliup-rs binary
#   xz-utils — required to extract .tar.xz archives
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ffmpeg \
        curl \
        xz-utils \
        fonts-noto-cjk \
        fontconfig \
    && rm -rf /var/lib/apt/lists/*

# Install biliup-rs (Bilibili upload CLI)
ARG BILIUP_VERSION=v0.2.4
RUN case "$(uname -m)" in \
        x86_64)  ARCH="x86_64-linux" ;; \
        aarch64) ARCH="aarch64-linux" ;; \
        armv7l)  ARCH="armv7-linux" ;; \
        *)       echo "ERROR: Unsupported architecture: $(uname -m)"; exit 1 ;; \
    esac && \
    curl -fSL \
        "https://github.com/biliup/biliup-rs/releases/download/${BILIUP_VERSION}/biliupR-${BILIUP_VERSION}-${ARCH}.tar.xz" \
        -o /tmp/biliup.tar.xz && \
    tar -xJf /tmp/biliup.tar.xz -C /tmp && \
    find /tmp -name biliup -type f -exec cp {} /usr/local/bin/biliup \; && \
    chmod +x /usr/local/bin/biliup && \
    rm -rf /tmp/biliup* && \
    biliup --version

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# The output/ directory is gitignored but must exist at runtime
RUN mkdir -p output

# Config file is required at runtime — instruct user to mount or copy one.
# Generate from config.example.json if not provided:
#   cp config.example.json config.json
# Or mount a host config:
#   -v /path/to/config.json:/app/config.json
# For Bilibili upload, also mount cookies.json (generated by: biliup login)

CMD ["python", "-u", "-m", "src.main"]
